### ISSUE TITLE
Minimal canvas example panics on Windows with debug assertions enabled

### ISSUE THREAD

**Issue by toolness** [servo/pathfinder#183]
When I configure Pathfinder to check GL errors based on `debug_assertions` as per #182, I've found that the latest `master` panics when running the minimal canvas example.  However, disabling the debug assertions causes everything to work fine.

I thought this might be relevant to #178, in that perhaps getting the minimal canvas example to run without panicking in debug mode might also fix whatever is at the root of #178, which could be easier than building the Unity plugin and stepping through it.

Anyways, here's the stack trace when running the minimal canvas example:

```
thread 'main' panicked at 'GL error: 0x501 (INVALID_VALUE)', gl\src\lib.rs:928:13
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:340
   9: pathfinder_gl::ck
             at C:\Users\Atul\Documents\explorations\pathfinder-c-api-fun\pathfinder\gl\src\lib.rs:928
  10: pathfinder_gl::{{impl}}::configure_vertex_attr
             at C:\Users\Atul\Documents\explorations\pathfinder-c-api-fun\pathfinder\gl\src\lib.rs:350
  11: pathfinder_renderer::gpu::renderer::AlphaTileVertexArray<pathfinder_gl::GLDevice>::new<pathfinder_gl::GLDevice>
             at C:\Users\Atul\Documents\explorations\pathfinder-c-api-fun\pathfinder\renderer\src\gpu\renderer.rs:1077
  12: pathfinder_renderer::gpu::renderer::Renderer<pathfinder_gl::GLDevice>::new<pathfinder_gl::GLDevice>
             at C:\Users\Atul\Documents\explorations\pathfinder-c-api-fun\pathfinder\renderer\src\gpu\renderer.rs:158
  13: canvas_minimal::main
             at .\src\main.rs:49
  14: std::rt::lang_start::{{closure}}<()>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libstd\rt.rs:64
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\rt.rs:49
  16: std::panicking::try::do_call<closure,i32>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:297
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libpanic_unwind\lib.rs:87
  18: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:276
  19: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panic.rs:388
  20: std::rt::lang_start_internal
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\rt.rs:48
  21: std::rt::lang_start<()>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libstd\rt.rs:64
  22: main
  23: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  24: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
error: process didn't exit successfully: `C:\Users\Atul\Documents\explorations\pathfinder-c-api-fun\pathfinder\target\debug\canvas_minimal.exe` (exit code: 101)
```

**Comment by toolness** [comment]
@pcwalton want me to look into fixing this? I might be way over my head because I don't have a lot of experience with OpenGL (in fact I've only really used WebGL) but it could be a nice way to learn more.  Don't want to step on any toes, though.

**Comment by pcwalton** [comment]
Sure, feel free to take a look!

**Comment by benpye** [comment]
I've just run this through with RenderDoc - it reports that we're exceeding the maximum number of vertex attributes:

![image](https://user-images.githubusercontent.com/442623/59142399-9cb69800-8972-11e9-8af3-d8d68fb67406.png)

I suspect this isn't a Windows issue but a driver compatibility issue, I'm running with Nvidia's drivers.

We are ending up with a bogus value for `color_tex_coord_attr` in `AlphaTileVertexArray::new()` - `0xFFFFFFFF`. The OpenGL docs indicate `If the named attribute variable is not an active attribute in the specified program object or if name starts with the reserved prefix "gl_", a value of -1 is returned.`

**Comment by toolness** [comment]
Oh awesome, thanks for looking into this @benpye!  For now I've just issued #193 to at least make these sorts of problems easier to diagnose.  And thanks for the tip about RenderDoc, I bet it will help for the Unity crash.

**Comment by toolness** [comment]
Ok, this is fixed as of the latest master, I _think_ because of dbf02fb742c6b673bb2f48188fbd054517dc02ed.  Thanks @pcwalton!  Closing now.
