### ISSUE TITLE
Assert running canvas_text example

### ISSUE THREAD

**Issue by emoon** [servo/pathfinder#231]
Hi,

I get this assert when I'm trying to run the `canvas_text` example on Linux (Rust `1.36.0`)

```
RUSTFLAGS="-C target-cpu=native" cargo run --bin canvas_text
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/canvas_text`
thread 'main' panicked at 'assertion failed: *current_point_index <= last_point_index_in_contour', /home/emoon/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.2.0/src/loaders/freetype.rs:576:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:408
   6: font_kit::loaders::freetype::Font::outline::get_point
             at /home/emoon/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.2.0/src/loaders/freetype.rs:576
   7: font_kit::loaders::freetype::Font::outline
             at /home/emoon/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.2.0/src/loaders/freetype.rs:534
   8: <font_kit::loaders::freetype::Font as font_kit::loader::Loader>::outline
             at /home/emoon/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.2.0/src/loaders/freetype.rs:1029
   9: <pathfinder_renderer::scene::Scene as pathfinder_text::SceneExt>::push_glyph
             at text/src/lib.rs:69
  10: <pathfinder_renderer::scene::Scene as pathfinder_text::SceneExt>::push_layout
             at text/src/lib.rs:97
  11: pathfinder_canvas::text::<impl pathfinder_canvas::CanvasRenderingContext2D>::fill_or_stroke_text
             at canvas/src/text.rs:69
  12: pathfinder_canvas::text::<impl pathfinder_canvas::CanvasRenderingContext2D>::fill_text
             at canvas/src/text.rs:30
  13: canvas_text::main
             at examples/canvas_text/src/main.rs:68
  14: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by s3bk** [comment]
Is is fixed in font-kit … the [fix](https://github.com/pcwalton/font-kit/pull/78) just needs to propagate through.
