### ISSUE TITLE
canvas_minimal example panics on ubuntu

### ISSUE THREAD

**Issue by shahreel** [servo/pathfinder#233]
<pre>ubuntu 19.04 with nvidia 8500 GT

RUST_BACKTRACE=1 RUSTFLAGS=&quot;-C target-cpu=native&quot; cargo run --bin canvas_minimal
<font color="#4E9A06"><b>    Finished</b></font> dev [unoptimized + debuginfo] target(s) in 2.69s
<font color="#4E9A06"><b>     Running</b></font> `target/debug/canvas_minimal`
thread &apos;main&apos; panicked at &apos;called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; })&apos;, src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result&lt;T,E&gt;::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: font_kit::source::Source::select_descriptions_in_family
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.2.0/src/source.rs:142
  11: font_kit::source::Source::select_best_match
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.2.0/src/source.rs:126
  12: pathfinder_canvas::text::CanvasFontContext::new
             at canvas/src/text.rs:147
  13: pathfinder_canvas::text::CanvasFontContext::from_system_source
             at canvas/src/text.rs:163
  14: canvas_minimal::main
             at examples/canvas_minimal/src/main.rs:55
  15: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  16: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  18: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  19: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  20: main
  21: __libc_start_main
  22: _start</pre>

**Comment by jdm** [comment]
This comes from [this line](https://github.com/pcwalton/font-kit/blob/9b5e6bd42e3742bf8b57cdd09c60058397ab13a1/src/source.rs#L109), which loads [this font name](https://github.com/pcwalton/font-kit/blob/9b5e6bd42e3742bf8b57cdd09c60058397ab13a1/src/source.rs#L56). This ends up calling [this code](https://github.com/pcwalton/font-kit/blob/9b5e6bd42e3742bf8b57cdd09c60058397ab13a1/src/source.rs#L141-L143) which has an unwrap.
