### ISSUE TITLE
Panic when attempting to use clip_path via canvas API with Metal

### ISSUE THREAD

**Issue by nathansobo** [servo/pathfinder#355]
I thought I'd share this stack trace. The application that generates it is closed source for now, but I can try to produce a test case if it's not already obvious from the stack trace what is occurring. I'm using [this fork](https://github.com/nathansobo/pathfinder/commits/zed) that deviates very slightly from master by adding a `CanvasRenderingContext2D::fill_glyph` method so I can perform text layout via CoreText.

```
03:00:06 [ERROR] thread 'main' panicked at 'Render pipeline state construction failed: Error Domain=CompilerError Code=2 "Vertex attribute aDestTileOrigin(1) of type int2 cannot be read using MTLAttributeFormatUChar2" UserInfo={NSL
ocalizedDescription=Vertex attribute aDestTileOrigin(1) of type int2 cannot be read using MTLAttributeFormatUChar2}': /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/metal/src/lib.rs:2133
stack backtrace:
   0: log_panics::init::{{closure}}::h1d9da0e394756071 (0x106854c8c)
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52
   1: std::panicking::rust_panic_with_hook::hf8b9378dd2e7986a (0x10703a2c5)
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:481
   2: _rust_begin_unwind (0x107039e71)
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:385
   3: std::panicking::begin_panic_fmt::h2e6dba6f5c07d155 (0x10706c96a)
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:339
   4: <metal::device::Device as pathfinder_metal::DeviceExt>::real_new_render_pipeline_state_with_reflection::h77ecba60b6e2d8f0 (0x106baa54c)
             at /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/metal/src/lib.rs:2133
   5: pathfinder_metal::MetalDevice::prepare_to_draw::h3286cae9bba58c8c (0x106b8ab96)
             at /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/metal/src/lib.rs:1147
   6: <pathfinder_metal::MetalDevice as pathfinder_gpu::Device>::draw_elements_instanced::hd31b3225fd4d3f50 (0x106b864e3)
             at /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/metal/src/lib.rs:691
   7: pathfinder_renderer::gpu::renderer::Renderer<D>::draw_clip_batch::h1540d6dcfad6c892 (0x106a15e01)
             at /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/renderer/src/gpu/renderer.rs:838
   8: pathfinder_renderer::gpu::renderer::Renderer<D>::render_command::{{closure}}::h18b600a90a823733 (0x106a1551a)
             at /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/renderer/src/gpu/renderer.rs:297
   9: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}::hb1bf06a385808040 (0x10691efef)
             at /Users/nathan/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:655
  10: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}::h299f072a0b12678f (0x10691e41f)
             at /Users/nathan/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:2002
  11: core::iter::traits::iterator::Iterator::try_fold::h8f2913ec559a6a8e (0x10690394c)
             at /Users/nathan/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:1878
  12: core::iter::traits::iterator::Iterator::fold::h4862e84901edff11 (0x10690242a)
             at /Users/nathan/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:2005
  13: core::iter::traits::iterator::Iterator::for_each::h31f3dd633033bb72 (0x106902fb6)
             at /Users/nathan/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:658
  14: pathfinder_renderer::gpu::renderer::Renderer<D>::render_command::h05f974549231d3c6 (0x106a152af)
             at /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/renderer/src/gpu/renderer.rs:297
  15: pathfinder_renderer::concurrent::scene_proxy::SceneProxy::build_and_render::h583f451c261531c0 (0x106a4d6bf)
             at /Users/nathan/.cargo/git/checkouts/pathfinder-cfe95cd613759ae4/f8074bf/renderer/src/concurrent/scene_proxy.rs:91
```

I can also give you access to my source code if it would be at all helpful in debugging this.

**Comment by pcwalton** [comment]
`aDestTileOrigin` should be gone now with the D3D11 backend, so this bug is fixed as stated. Feel free to reopen if you see this issue again.

**Comment by nathansobo** [comment]
Thanks very much! I will give the latest master a try soon and report back if I'm still hitting this.

**Comment by nathansobo** [comment]
Looks like we're running into the issue with running the Metal code in the presence of an autorelease pool, so we'll have to give it another try once that's resolved.
